services:
  final:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      target: final
    environment:
      CONNECTION_STRING: Host=db;Port=5432;Database=iotbaydb;Username=iotbay;Password=password
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Release
    ports:
      - "8080:8080"
    networks:
      - iotnet