services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: iotbay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iotbaydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iotnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iotbay -d iotbaydb"]
      interval: 5s
      retries: 5
      start_period: 5s

networks:
  iotnet: