services:
  iotbay:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      target: dev
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: true
      DOTNET_DEBUG: 1
      DOTNET_WATCH: 1
      CONNECTION_STRING: Host=db;Port=5432;Database=iotbaydb;Username=iotbay;Password=password
      ASPNETCORE_URLS: http://+:8080
      HTTP_PORTS: ""
      HTTPS_PORTS: ""

    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - iotnet