namespace IoTBay.Models.Views;

/// <summary>
/// Auto generated by ASP.NET Core.
/// </summary>
public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}